on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - release

permissions: write-all

name: ğŸ“¦ Publish Release
jobs:
  update-changelog:
    name: ğŸ“ Manage Release Publish
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v3

      - name: ğŸ”– Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: main

      - name: ğŸ”– Set tag to latest commit
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.semver.outputs.next }}
          tag_exists_error: false
          message: ''

      - name: ğŸ“ Generate Changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          excludeTypes: ''
          includeInvalidCommits: true
          token: ${{ github.token }}
          tag: ${{ steps.semver.outputs.next }}
          writeToFile: false

      - name: ğŸ“¦ Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semver.outputs.next }}
          release_name: ${{ steps.semver.outputs.next }}
          body: ${{ steps.changelog.outputs.changes }}
          draft: false
          prerelease: false
